### ISSUE TITLE
Different color of the fill between the slash and the keywords

### ISSUE THREAD

**Issue by 4174** [fabiospampinato/vscode-highlight#1]
Hi, it's cool extension, thank You!

In my case there are:
![image](https://user-images.githubusercontent.com/99181/38358703-0ce8fbec-38d7-11e8-8346-955dddf6824a.png)

**Comment by 4174** [comment]
Use from README.md (for TODO, FIXME, @param).
![image](https://user-images.githubusercontent.com/99181/38409880-3138e166-3994-11e8-86c4-47df7ee2fb5a.png)
It's OK without ":".

**Comment by fabiospampinato** [comment]
I think you have [TODO Highglight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) installed on your system, that pinkish color looks familiar to me.

I'm definitely biased here, but I think you should replace that extension with this and [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus)

**Comment by 4174** [comment]
You are right, thanks, be happy)
