### ISSUE TITLE
HTML focused regex not working as expected and/or perhaps some suggestions on how I can improve my regex for this. 

### ISSUE THREAD

**Issue by thedonquixotic** [fabiospampinato/vscode-highlight#10]
Hey Fabio, 

Really been enjoying using your extension. I've learned quite a bit of regex playing with it! But I'm having some trouble really nailing down my html focused regex. 

I've read widely that html regex is hard to do, or bad to do, but I feel so close I can taste it. Perhaps you might be able to suggest what I could do better? 

This should work I think... but it doesn't:

`(<)([.\n]*)(>{1})([.|\n]*)(<\\/)([.|\n]*)(>)`

And this kind of works but it can't handle more complex things where there are both line breaks and letters/spaces:

`(<)(.*|\n*)(>{1})(.*|\n*)(<\\/)(.*|\n*)(>)`

Just tried this one and it kinda works but seems to be a little buggy:

`(<)([\\s\\S]*?)(>{1})([\\s\\S]*?)(<\\/)([\\s\\S]*?)(>)`

**Comment by thedonquixotic** [comment]
Also found this solution `</?\w+((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[\^'">\s]+))?)+\s*|\s*)/?>` [[here]](https://haacked.com/archive/2004/10/25/usingregularexpressionstomatchhtml.aspx/)

But not sure how to fit it into the settings since double quotes are not allowed.

**Comment by fabiospampinato** [comment]
I'm currently on vacation so I can't really test these regexes for you, but I'll try to answer some of the questions. 

> I've read widely that html regex is hard to do, or bad to do, but I feel so close I can taste it. 

I think it's impossible to have a regexes that always works for any arbitrary html string. 

> Perhaps you might be able to suggest what I could do better?

If you could provide me some examples of what you're actually trying to match and how you want it highlighted maybe I could help. 

> But not sure how to fit it into the settings since double quotes are not allowed.

Every character is allowed, you just have to escape some of them (double quotes, backslashes). 

> I don't believe that can work with your extension though as not everything is in a capture group, right?

Yeah, decorations will be misaligned. But it should be trivial to just wrap everything that's not already in a matching group in new matching groups.

**Comment by thedonquixotic** [comment]
Thanks @fabiospampinato I figured it out! This is the solution I ended up using. I got a good night sleep it much clearer in the morning!

```
//- Opening Tag
    "(<[^\\/!%=]*?)([^!%(</)](.|\n|\r)*?)(>)": [
      { 
        "borderWidth": "1px 0 1px 4px",
        "borderStyle": "solid",
        "borderColor": "rgba(255, 103, 123, 0.5)",
        "borderRadius": "0px",
        "backgroundColor": "rgba(33, 24, 28, 0.6)",
        "color": "#d44040",
        "fontStyle": "bold",
        "fontWeight": "bold",
      },

      { 
        "backgroundColor": "rgba(26, 18, 26, 0.4)",
        "borderWidth": "1px 0px 0px 0",
        "borderStyle": "solid",
        "borderColor": "rgba(255, 103, 123, 0.5)",
        "borderRadius": "0px",
      },

      { 
        "backgroundColor": "rgba(15, 21, 31, 0.45)",
        "color": "rgba(40, 68, 85, 0.7)"
      },

    ],
    //- Closing tag
    "(<\\/)((.|\n|\r)*?[^\\/])(>)": [
      { 
        "backgroundColor": "rgba(15, 21, 31, 0.45)",
        "color": "rgba(40, 68, 85, 0.7)"
      },

      { "borderWidth": "0px 0px 1px 0",
        "borderStyle": "solid",
        "borderColor": "rgba(255, 103, 123, 0.5)",
        "borderRadius": "0px",
        "backgroundColor": "rgba(26, 18, 26, 0.4)",
        
      },

      { 
        "borderWidth": "1px 4px 1px 0",
        "borderStyle": "solid",
        "borderColor": "rgba(255, 103, 123, 0.5)",
        "borderRadius": "0px",
        "backgroundColor": "rgba(33, 24, 28, 0.6)",
        "color": "#d44040",
        "fontStyle": "bold",
        "fontWeight": "bold",
      },
    ],
  
```

I realized that it was much simpler to try and look for opening and closing tags separately rather than trying to do one big thing, and since my purpose was not to actually do any tag matching per se, it worked much better!Trying to include anything and everything between the two tags would inevitably lead to everything getting captured or nothing I believe, due to the nested nature of HTML. Though I've got an idea I'm going to try out. For now though, this works as I want it too!
