### ISSUE TITLE
Support text-shadow (for glowing text)

### ISSUE THREAD

**Issue by chavlji** [fabiospampinato/vscode-highlight#101]
Glowing text draws much more attention. This is exactly what we need sometimes.
Please add support for `text-shadow` property.

**Comment by fabiospampinato** [comment]
Only whatever VS Code itself supports can be supported, other properties can not be implemented.

**Comment by chavlji** [comment]
Q: How can you then set the background color? VS Code themes do not support it.

**Comment by fabiospampinato** [comment]
Everything supported is listed here: https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

There's a `backgroundColor` option.
