### ISSUE TITLE
Something confusing in the example

### ISSUE THREAD

**Issue by mnieber** [fabiospampinato/vscode-highlight#102]
Hi Fabio, thanks for this extension, it's working well for me. I had to overcome a small confusion though when trying to follow your example:

```
 "(//TODO)(:)": { // A regex will be created from this string, don't forget to double escape it
```

When I read this, I tried to look for the "double escape" and I thought that it must be the `//` that appears before TODO. This is of course not an escape at all, but this is the brainfuck I had (pardon my french). So initially, I didn't even think of trying to type "//TODO" to see if the extension works or not (I couldn't make it work, and when I added // to my try-out text then everything clicked).

**Comment by noisnemid** [comment]
```(//TODO)(:)```
that is the example of highlight-extension.

```// A regex will be created from this string, don't forget to double escape it```
this is the comment for the config json file(vscode's json support comments).

```\\.+```
this is called double escaped, which is needed by javascript / typerscript.
which means 
```\.+``` to a regex engine.

**Comment by mnieber** [comment]
Yes, I know, I just thought you might want to change the example to avoid the potential confusion. Up to you of course.

**Comment by fabiospampinato** [comment]
Regex embedded in JSON with comments are somewhat confusing by themself, I don't think there's a way that I can see to make the extension or the examples much easier to use, like one will probably have bigger issues when trying to use the extension anyway, if that example is confusing already it may be a nice sort of warm up 😄
