### ISSUE TITLE
Stops working in large files

### ISSUE THREAD

**Issue by Helyk** [fabiospampinato/vscode-highlight#104]
I tried using the extension to highlight different loglevels in logs, for example:
```
"level":"info"
"level":"debug"
"level":"warning"
"level":"error"
```

The setting that I made for that look like this:
```json
"(level\":\")(error)\"": {
    "filterLanguageRegex": "json",
    "decorations": [
        {},
        {
            "color": "#FF5370"
        }
    ]
},
```

Obviously, matches for that occur in every single line of logs. It works correctly in files with a few hundred lines but in larger files, for example with 20-30 thousand lines, I only see a few lines having the configured highlight.

**Comment by dimateos** [comment]
If you did not notice the setting, then you are definitely hitting the default matches limit:
```jsonc
"highlight.maxMatches": 250 // Maximum number of matches to decorate per regex, in order not to crash the app with accidental cathastropic regexes
```

**Comment by fabiospampinato** [comment]
As @dimateos said.

> But this setting is global tho. Maybe it could be overwritten per regex (like regexFlags) for exceptions like this.

Maybe, it doesn't seem super necessary. It's mainly a stop gap against broken regexes, one can just keep it low while tweaking things, and then raise it once things are working properly.
