### ISSUE TITLE
doens't lightlight

### ISSUE THREAD

**Issue by quantrpeter** [fabiospampinato/vscode-highlight#106]
hi 
   it doesn't highlight the word "sifive_plic_read" in "qemu_plic.log". do i need to activate something? thx

"sifive_plic_read": {
            "filterFileRegex": "qemu_plic.log",
            "decorations": [
                {
                    "overviewRulerColor": "#cc00cc",
                    "backgroundColor": "#cc00cc",
                    "color": "#1f1f1f",
                    "fontWeight": "bold"
                },
                {
                    "backgroundColor": "#cc00cc",
                    "color": "#1f1f1f"
                }
            ]
        }

**Comment by fabiospampinato** [comment]
Any parts of the regex must be wrapped in a capturing block, so in this example it should probably be "(sifive_plic_read)", not "sifive_plic_read"
