### ISSUE TITLE
filterFileRegex dont seem to work for negative look ahead

### ISSUE THREAD

**Issue by dimateos** [fabiospampinato/vscode-highlight#107]
Following #6 `"filterLanguageRegex": "^(?!makefile)"` works for lang id.
But if I try to use it to match the file path with `filterFileRegex` it does not work.

```groovy
// hits the color regex or not?
red

// path of the file
D:\Archivos\Downloads\makefile.txt

// might break at ":", because when using "filterLanguageRegex": "^(?!d)" the file gets ignored
```

Maybe I am doing something wrong with the regex? (regex globals gi)
Thanks for the help!

**Comment by fabiospampinato** [comment]
Wait what's the path you are matching against and what's the regex? Most probably the regex is just matching other parts of the path you didn't think about, maybe.

**Comment by dimateos** [comment]
_Hey, just re-checked it out and solved it._

The path was the one described in the contents of the file:

```c
// hits the color regex or not?
red

// path of the file
C:\Users\Diego\Downloads\makefile.txt
``````

The whole rule was the one to match colors from the examples but just added the filter:

```jsonc
"(?<!\\w)(#[a-f0-9]{3,4}|#[a-f0-9]{6}|#[a-f0-9]{8}|rgba?\\s*\\([^)]*?\\)|hsla?\\s*\\([^)]*?\\)|aliceblue|antiquewhite|...(?!\\w)": {
    //"filterLanguageRegex": "^(?!makefile)",   // works, ignoring the file (lang_id must be set to makefile not plaintext)
    //"filterFileRegex": "^(?!makefile)",       // did not work, only matched the beginning of the path
    "filterFileRegex": "^(?!.*makefile)",       // now works

    "regexFlags": "gi",
    "decorations": [{
        "rangeBehavior": 1,
        "borderWidth": "2px",
        "borderColor": "$1",
        "borderStyle": "solid",
    }],
},
```

The problem was kind of what I hinted. `"^(?!makefile)"` was not breaking, it just could only match "makefile" at the beginning of the path. After adding `.*` inside the negative look-ahead it works.

Cheers

**Comment by fabiospampinato** [comment]
Thanks for the update 👍
