### ISSUE TITLE
Decorators are not cleared until next occurrence created

### ISSUE THREAD

**Issue by antontkv** [fabiospampinato/vscode-highlight#109]
Hi, I hope you having a lovely day.

I'm using this setting to detect trailing white space:

```json
"([ \\t]+$)": {
    "regexFlags": "gm",
    "decorations": [
        { "color": "red" }
  ]
}
```

Coupled with vscode setting `"editor.renderWhitespace": "boundary"` it clearly marks trailing white space red:

![image](https://user-images.githubusercontent.com/17809291/216056730-41bf4f0f-2097-46a0-9a76-79f951ad943c.png)

But on the 1.7.1 version there is a bug, that the word after space will be red until next space is entered:

![171](https://user-images.githubusercontent.com/17809291/216058035-33d6cc47-5ef0-4f15-a722-6f114b2c766a.gif)

And this is on 1.7.0 version, were there is a slight delay, when the first letter is red, but it quickly updates color and overall works fine:

![170](https://user-images.githubusercontent.com/17809291/216059266-f2e5c29a-278f-4b3c-982e-71d68e97277a.gif)

**Comment by alexwall** [comment]
Hi @antontkv, 

to fix this in 1.7.1 you can change the rangeBehvaoir to 2 (default is 3). 

```json
    "highlight.decorations": {
        "rangeBehavior": 2
    },
```
I've tested it with this settings an it works for me. @antontkv do you mind to verify that the config works also for you?

@fabiospampinato you provided this solution yesterday in your [comment](https://github.com/fabiospampinato/vscode-highlight/issues/76#issuecomment-1410799112) ;). 

 So two proposals:

1. Revert logically back to 1.7.1 and change default value for `rangeBehavior` to 2. I mean `rangeBehavior: 3`  does not work as I would expect Highlight to work, see my explanation in [this comment](https://github.com/fabiospampinato/vscode-highlight/issues/76#issuecomment-1410799112).
2. If proposal 1) is not an option for you, let's make `undecorade` as an option. With a default value `true` if you prefer the behaviour of previous version as default, or `false` if you are convinced that the [flickering bug](https://github.com/fabiospampinato/vscode-highlight/issues/105) has a higher priority.

**Comment by antontkv** [comment]
> to fix this in 1.7.1 you can change the rangeBehvaoir to 2 (default is 3).

This fixes this, but introduces other problem. The decoration is not cleared when regex is no longer matches until new match entered. Whitespace stays red, even though it no longer trailing.

![171_2](https://user-images.githubusercontent.com/17809291/216087570-f3e46c0e-355f-43e2-9ad1-575cce9a2772.gif)

**Comment by alexwall** [comment]
@antontkv having a closer look at [the vscode API](https://github.com/vscode-cn/vscode-api-cn/blob/1f372d69599a5f2977586e7548f5604a92a78b23/vscode.d.ts#L744), I think you have to use 

```    
  "highlight.decorations": {
        "rangeBehavior": 1
    },
```

Please change it and restart/reload your vscode window.

**Comment by antontkv** [comment]
@alexwall Still the same problem like with 2.

**Comment by alexwall** [comment]
Ok this is strange, because I can't reproduce your issue with this settings. @antontkv is it possible that you have other regular expressions that could produce side effects here? Other regular expressions regarding white spaces?

@fabiospampinato What do think regarding my proposal 2. It wouldn't affect other people and provide the opportunity to stay up-to-date with your extension.

**Comment by alexwall** [comment]
@antontkv I've watched your screencast again and recognised, that the first dot (white space) is darker than the others. 
I don't get a _first_ dark red dot with your regex, so my assumption is that you have another regex that creates this side effect.

Here my full settings:

```json

    "highlight.decorations": {
        "rangeBehavior": 1
    },
    "highlight.minDelay": 150,
    "highlight.regexFlags": "gi",
    "highlight.maxMatches": 500,
    "highlight.regexes": {
      "([ \\t]+$)": {
          "regexFlags": "gm",
          "decorations": [
              { "color": "red" }
        ]
      }
},
```

Here my screencast:
https://user-images.githubusercontent.com/316469/216126173-75e64819-e0b7-4201-bc67-3c438e961451.mov

**Comment by antontkv** [comment]
@alexwall The first dot only appears darker on screen cast, probably because of gif compression. I removed all my `highlight` setting and appalled yours. Still have the problem. Based on your screen cast I noticed that you don't have `"editor.renderWhitespace": "boundary"` setting enabled. Try with it, since it will render all whitespace in the document, except one space between words.

**Comment by alexwall** [comment]
@antontkv thank you for providing that information. In fact I could reproduce this issue with your configuration. 
And I'm happy to announce that I could also figure it out... 
I've provided the fix in this PR: https://github.com/fabiospampinato/vscode-highlight/pull/110

BTW: It works for all values of `"rangeBehavior": `, but my suggestion is to use `"rangeBehavior": 1` ([ClosedClosed](https://vscode-api-cn.js.org/enums/vscode.DecorationRangeBehavior.html)), at least this option makes the most sense to me. But it's irrelevant for this fix....

@fabiospampinato do mind to review and release a new version of highlight? Thanks in advance.

**Comment by alexwall** [comment]
@fabiospampinato to be more precise, the optimisation in PR: https://github.com/fabiospampinato/vscode-highlight/pull/110
provides 100% equal decorations as in version 1.7.0 which is calling `undecorate`, while it's calling `.setDecoration()` up to 50% fewer. So it won't break anything 😉

**Comment by fabiospampinato** [comment]
@alexwall I'm a little busy at the moment, give me a few days and I'll see if we can merge the new PR 👍
