### ISSUE TITLE
Handling OR in regex

### ISSUE THREAD

**Issue by janilahti** [fabiospampinato/vscode-highlight#11]
I took this demo definition:
`"(// ?TODO:?)(.*)": [`
and added OR part to handle both `//` and `#` style comments:
`"((//|#) ?TODO)(.*)": [`
The extension gives:
![todo-example-fail1](https://user-images.githubusercontent.com/3872914/42149457-d234cbb4-7dde-11e8-8383-27e7fd101554.png)
If I add empty `{}` in middle of the decorations array, I get:
![todo-example-fail2](https://user-images.githubusercontent.com/3872914/42149512-0b09be04-7ddf-11e8-84b1-1b1118ae3030.png)
If I try:
`"(//|# ?TODO)(.*)": [`
OR works but this catches all comment lines:
![todo-example-fail3](https://user-images.githubusercontent.com/3872914/42150753-663d8e50-7de3-11e8-8636-e36377dcc1a5.png)
Is there a suitable way to write OR regex or it this a bug?

**Comment by fabiospampinato** [comment]
Any kind of regex supported by JavaScript is supported by this extension.

You should just use the provided regex in the readme for matching todos, it's much more advanced than the one used in the demo and handles your use case as well as many others. 

Your second screenshot looks wrong, I don't understand why the columns are not highlighted, maybe you had to close and reopen the file to refresh the decorations or something. 

You can write your "or" condition like this: `(?:#|//)`, basically avoiding creating any new capturing groups. 

I think there might be an issue with nested capturing groups, so maybe avoid doing that.

**Comment by fabiospampinato** [comment]
I've added a note about nested capturing groups in the readme 👍
