### ISSUE TITLE
feature request: right click to quickly add/remove words for color toggle

### ISSUE THREAD

**Issue by imthenachoman** [fabiospampinato/vscode-highlight#113]
I'm hoping to make this extension easier to use for folks who aren't big coders but use VS Code for things like editing configuration files or looking at log files.

It would be nice if we could select some text, right click and have the extension start coloring it. 

Even better would be if we could select text, right click, tell the extension to color this text, and a color picker shows up to let us pick the color. 

cc: @jgarvas

**Comment by fabiospampinato** [comment]
Out of scope, but an interesting idea for a more approachable extension. If you don't need regexes I think there might already be way simpler extensions that you could use 🤔

**Comment by imthenachoman** [comment]
Out of curiosity, what do you mean by "Out of scope"? 

And I didn't find any other extensions like this but I will check some more. Thank you!

**Comment by jgarvas** [comment]
After reading the first reply here I found Text Highlighter does this
requested enhancement and does it quite well.

I think he meant it’s out of scope of what he wants this extension to offer.

**Comment by imthenachoman** [comment]
Oh, nice!
