### ISSUE TITLE
[FR] Support new CSS color syntax with the alpha component after `/`

### ISSUE THREAD

**Issue by wenfangdu** [fabiospampinato/vscode-highlight#115]
[CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#color-syntax) specifies a new syntax for color functions like `rgb`, `hsl` etc. which allows omitting commas and specifying alpha component by appending `/ <alpha>` value. So legacy color function like `rgba(0, 0, 0, 0.5)` could be rewritten like `rgb(0 0 0 / 50%)`.

**Comment by fabiospampinato** [comment]
The demo configuration I use for highlighting colors is out of scope of the extension, it's there as a demo. I should personally add support for that, if I do I'll try to remember to update the readme.
