### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by x0111** [fabiospampinato/vscode-highlight#116]
- Issue Type: `Performance`
- Extension Name: `vscode-highlight`
- Extension Version: `1.7.3`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/x0111/AppData/Local/Temp/fabiospampinato.vscode-highlight-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by fabiospampinato** [comment]
The file you were meant to attach didn't get attached, so there's nothing actionable here.
