### ISSUE TITLE
Android Studio version

### ISSUE THREAD

**Issue by HeropolisDa2ny** [fabiospampinato/vscode-highlight#119]
Hi,
By searching how to comment .arb files I found this topic : https://medium.com/codex/flutter-writing-comments-in-arb-files-8d113f10e4b9, selling the merits of using your plugin.

However, as a mobile developer I am using Android Studio.
Is there a version for Android Studio or will you do one ?

Thanks.

**Comment by fabiospampinato** [comment]
I don't use Android Studio myself so I don't know if there's a similar plugin for that and I don't currently plan on porting it to Android Studio. It'd be cool if somebody ported it though.
