### ISSUE TITLE
Highlights disappearing

### ISSUE THREAD

**Issue by SuperMB** [fabiospampinato/vscode-highlight#120]
We use the Highlight extension to format code that our tools generate. Overall, it works great! We are having an issue with the extension being used in python notebooks. Once a cell in the notebook goes out of view, the highlighting is no longer applied until the cell is clicked on. I think this has to do with each cell being its own editor. Ideally, when a cell comes back into view, it should have the regexs and formatting applied. 

We are currently working around this by detecting when new editor comes in view and adding an empty snippet to the cell. However, this causes the cell to get focus, which can be an issue. Please let me know if you would like me to upload a video of the behavior.

**Comment by fabiospampinato** [comment]
I think a similar issue happens with regular split editors also. I suspect it may be a bug in vscode 🤔

**Comment by SuperMB** [comment]
Wouldn't be too surprised if there's an issue within vscode. Let me know if there's anything I can share that would be helpful / the code we are currently using to "patch" it.

**Comment by SuperMB** [comment]
@fabiospampinato Following up on this, would it be possible for the time being just to expose an external function that can be called to refresh the highlights for an editor or all visible editors?

**Comment by fabiospampinato** [comment]
@SuperMB Maybe, but when would you trigger it? I think if you can fork the extension and expose that command, and if that fixes the problem reasonably well for you, then I can merge the change.

**Comment by SuperMB** [comment]
@fabiospampinato Well, I went ahead and took a quick look. I was able to expose the needed functionality, it's working MUCH better for us! Created a pull request, let me know if you have any questions about the edits. Will love it once the edit is published.

**Comment by SuperMB** [comment]
@fabiospampinato Just keeping this on your radar. Let me know if you have any questions on the Pull Request, would love to see the forceDecorate published soon!

**Comment by fabiospampinato** [comment]
`highlight.forceDecorate` command shipped in v1.9.0.
