### ISSUE TITLE
Option to add highlighted content to "Problems" tab

### ISSUE THREAD

**Issue by Arkkimaagi** [fabiospampinato/vscode-highlight#13]
I'm migrating from Sublime text to VSCode and trying to find solutions to missing plugins. With your plugin I was able to simulate https://github.com/TuureKaunisto/highlight-dodgy-chars by adding this setting:

```json
  "highlight.regexes": {
    "([^€£¡¿äàáâãåǎąăæçćĉčđďðèéêëěęĝģğĥìíîïıĵķĺļłľñńňöòóôõőøœŕřẞßśŝşšșťţþțüùúûűũųůŵýÿŷźžż\u0000-\u007F])": [
      {
        "backgroundColor": "#ff0000",
        "overviewRulerColor": "#ff0000",
      }
    ]
  },
```

The regex matches all non-ascii characters except the ones listed in the regex. This way I can see if I accidentally type a non breaking character to my code (on mac it's alt+space) or any other weird character.

What would be extra cool, is to see all the matches of these unwanted ascii characters in the "Problems" tab of vscode.

So if I'd modify my settings to be:
```json
  "highlight.regexes": {
    "([^€£¡¿äàáâãåǎąăæçćĉčđďðèéêëěęĝģğĥìíîïıĵķĺļłľñńňöòóôõőøœŕřẞßśŝşšșťţþțüùúûűũųůŵýÿŷźžż\u0000-\u007F])": [
      {
        "backgroundColor": "#ff0000",
        "overviewRulerColor": "#ff0000",
        "showInProblemsTab": true,
        "Description": "Unwanted character found",
      }
    ]
  },
```
In the problems tab I'd see:
```
index.html:
    [highlight] Unwanted character found: " " (6,1)
```
And it would be faster to spot these problems in my files.

What do you think?

**Comment by fabiospampinato** [comment]
I like the generality of your approach, one could also use this for finding todos and whatnot.

But I personally don't think I would use it, I already use [Todo+](https://github.com/fabiospampinato/vscode-todo-plus) for finding todos and there isn't anything else I'd like to search for this way. Also unless you're using a multi-line regex, or you're using this functionality often, you could just do a global search via VSCode.

Thanks for the suggestion, if I decide to code something like that I'll update this thread.
