### ISSUE TITLE
Capture more than one word.

### ISSUE THREAD

**Issue by muuvmuuv** [fabiospampinato/vscode-highlight#14]
This is not a bug, rather more a question: I trying really hard to get this regex here working

```
((?:<!-- *)?(?:#|//|/\\*+|<!--|--) *(TODO|NOTE):?)(?!\\w)((?: +[^\n@]+?)(?= *(?:[^:]//|/\\*+|<!--|@|--))|(?: +[^@\n]+)?)
```

It is hard to debug a regex like this, when there is no live tester for ripgrep (or I just not know one). Note the `(TODO|NOTE)` capturing group. For sure it highlights both but on an empty comment with `TODO:` it also highlights the next line too.

![screenshot 2018-08-13 at 08 47 05](https://user-images.githubusercontent.com/11534760/44016491-7ac4909a-9ed5-11e8-9809-c7b322ac210f.png)

**Comment by fabiospampinato** [comment]
@muuvmuuv I use https://regex101.com/ for testing my regex.

If you want to use that with ripgrep just remember that it doesn't support lookarounds, so `(?=` (positive lookahead) and `(?!` (negative lookahead) in that regex won't work with ripgrep.

Btw this extension doesn't use ripgrep.

I see you're highlighting stuff like `FIXME` and `REMOVED`, but there's no mention about those in the regex you posted, are you using a different one in your settings?

**Comment by muuvmuuv** [comment]
That did it, thanks!

**Comment by fabiospampinato** [comment]
Maybe the problem was that you added another campuring group by doing `(TODO|NOTE)`.

**Comment by muuvmuuv** [comment]
Yep, I think that was my problem, but I'm so unfamiliar with regexes and glops that I couldn't get it working. Btw great work! Tested many todo plugins and yours seems to work as I expect a todo plugin to work.

**Comment by fabiospampinato** [comment]
Thank you :)
