### ISSUE TITLE
Regex help

### ISSUE THREAD

**Issue by pgmlloyd** [fabiospampinato/vscode-highlight#146]
Im looking for some simple help. Ive worked with regex, but Im far from competent with it. 

I would like to highlight parts of my code, but I cant seem to get the regex right. For example, I would like to highlight the word "ADD" (both upper & lower). I would like just the word ADD highlighted. Meaning the code will have a space before and after the string. I dont want words that contain ADD to highlight, only that exact string. What would the regex look like to accomplish this? 

Thanks

**Comment by fabiospampinato** [comment]
You could try something like this: `\b(ADD|add)\b`, where you need to escape the escapes when inserting it in the settings file: `\\b(ADD|add)\\b`
