### ISSUE TITLE
Formatting the file dispels highlighting

### ISSUE THREAD

**Issue by Alxandr** [fabiospampinato/vscode-highlight#15]
I have todo highlighting enabled, but when I format the file (using prettier), it removes the highlighting until I type another character in the line that has the TODO. This means that whenever I save, all the highlights vanishes.

**Comment by fabiospampinato** [comment]
> I have todo highlighting enabled

You mean "highlight"?

Can you paste your exact highlight/prettier settings?

**Comment by Alxandr** [comment]
highlighter:
```json
"((?://|#) ?TODO:?)(.*?)\\n": [
      {
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      }
    ],
```

other settings:
```json
"editor.tabSize": 2,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "window.zoomLevel": 0,
  "editor.formatOnSave": true,
  "workbench.iconTheme": "vs-nomo-dark",
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
```

From what I observe, whenever I save, the whole file/editor/pane does a small "jump" (like you copy-pasted the entire code in again, seems the entire file is re-rendered). Oh, and thinking about it, it might not be prettier, but might be import sorter that does it.

**Comment by fabiospampinato** [comment]
I can't reproduce this.

Please write some precise reproducible steps, perhaps try to reproduce this starting with a clean VSCode installation, basically download the Insiders version and try to reproduce it there.

**Comment by Alxandr** [comment]
Figured it out. It's caused by `amatiasq.sort-imports`. Your extension was just the one where it was easiest to spot the issue.

**Comment by fabiospampinato** [comment]
👍
