### ISSUE TITLE
Block comments (multi line)

### ISSUE THREAD

**Issue by duranivan** [fabiospampinato/vscode-highlight#16]
Hi and thanks for an awesome and flexible extension.

I was wondering if there is a way to highlight within block comments, something like this:

```js
/* 
todo:
*/
```

I know I could add generic regex to catch something like `* todo`, and write my block comments as

```js
/* 
* todo:
*/
```

But was wondering if there is a way to capture the first example with a regex.

Thanks in advance!

**Comment by fabiospampinato** [comment]
Sure, you need multi-line regex. You need to add the `m` flag to your regex's flags. 

For example: use `regexFlags": "gmi"` instead of `regexFlags": "gi"`.

**Comment by duranivan** [comment]
Thanks for the suggestions, however I haven't been able to have it work around with `"regexFlags": "gmi". Would you mind sharing an example in which the above block comment would work with the flag `gmi`?

I have the following which kind of works independent of `gmi`. The only problem is that if a one block comments follows a one line block comment, then it doesn't work:

```
"highlight.regexes": {
    // one line comment
    "((?:#|//|'''|\"\"\"|/\\*) ?TODO:?)(.*)": [
      {
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      },
    ],
   // Block comment
    "((?:'''|\"\"\"|/\\*)(?:[\\s\\S]*?))(TODO:?)(.*)((?:[\\s\\S]*?)(?:'''|\"\"\"|\\*/))": [
      {},
      {
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      },
    ]
}
```


Some examples here:

This works (one line comment followed by block comment)

![block_comment_highlight2](https://user-images.githubusercontent.com/20104703/46181251-11164300-c2de-11e8-969b-4f32fc9dfd41.png)

This doesn't work (block comment is not captured if follows a one line block comment)

![block_comment_highlight3](https://user-images.githubusercontent.com/20104703/46181348-b3362b00-c2de-11e8-8a1c-d1096aadf92b.png)

**Comment by fabiospampinato** [comment]
Can you post a sample text that should be matched? I'll try to craft a proper configuration for it tomorrow.

**Comment by duranivan** [comment]
Sure, here it is:

```
/*
Some text here

[todo:][ blahblahblah]
*/

/*
[todo:][ blahblahblah]
*/
```

The lines with brackets should be matched (first bracket with as group one, second bracket as group two)

**Comment by fabiospampinato** [comment]
This configuration:

```json
    "(^|\\n\\s*)(TODO:?)(.*)(?=[^]*\\*\\/)": [
      {},
      {
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      }
    ]
```

Properly matches this text:

```
/*
Some text here

  todo: blahblahblah
*/

/*
todo: blahblahblah
*/

/*
todo: blahblahblah
todo: blahblahblah
todo: blahblahblah
*/
```

<img width="177" alt="screen shot 2018-09-28 at 23 54 58" src="https://user-images.githubusercontent.com/1812093/46235283-f2658a00-c379-11e8-90b1-e4dc423dcaa7.png">

> Sure, you need a multi-line regex. You need to add the m flag to your regex's flags.

Actually this was wrong, that's not how the `m` flag works, sorry about that.

**Comment by duranivan** [comment]
Thanks a lot! Will try it out.
