### ISSUE TITLE
First Character? 

### ISSUE THREAD

**Issue by Philiphlop** [fabiospampinato/vscode-highlight#18]
Hello,

I have the regex working fine, but the styling is being applied to both the text characters and the space character. Is there a way to have the space character not show? 

```
This line does not have white space character
- This line does have white space character
# This line does have white space character
```

Results in
```
This line does not have white space character
-·This·line·does·have·white·space·character
#·This·line·does·have·white·space·character
```

Here is the config
```
"([^a-zA-Z0-9])([#][ ].*)": {
  "filterLanguageRegex": "markdown",
  "decorations": [
    {},
    {
      "isWholeLine": true,
      "backgroundColor": "rgba(255,0,0,0.25)",
      "color": "white",
      "font-weight": "bold"
    }
  ]
}
```

I am trying to make my own custom markdown syntax, as I haven't found an extension flexible enough for me, where I want different styles based on level (H1, H2, H3. li1, li2, li3, etc). If there is an extension more appropriate for this please point me that way.

**Comment by fabiospampinato** [comment]
Do you have `editor.renderWhitespace": "all"` in your settings?

**Comment by Philiphlop** [comment]
Bingo. I did, can't remember what for, but removing this has corrected it. I didn't expect that to be the issue, as non formatted text did not show a dot. Thank you :+1:
