### ISSUE TITLE
Ability to set 4/8 digit hex colors

### ISSUE THREAD

**Issue by usernamehw** [fabiospampinato/vscode-highlight#19]
Issue Type: <b>Feature Request</b>

`"backgroundColor": "#f06291aa",` - doesn't render decoration.

**Comment by fabiospampinato** [comment]
We support everything that's supported by VSC itself https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions .

You should probably open an issue about that in VSC's repo.

In the meantime I think you can use `rgba()` if you want to set the opacity.
