### ISSUE TITLE
OverviewRuler color blocking similar selection-highlight block

### ISSUE THREAD

**Issue by kotakerdus** [fabiospampinato/vscode-highlight#2]
Perhaps move it to the edge?

![image](https://user-images.githubusercontent.com/33751190/38371315-7aaa26a8-392f-11e8-9a60-204824298206.png)

 There is small gray block (similar selection-highlight feature) just below the highlighted line

**Comment by fabiospampinato** [comment]
You can use the `overviewRulerLane` option described [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions) and have it rendered in whichever lane you like.

**Comment by kotakerdus** [comment]
Ahh.. didnt know that option exist, thanks that was handy 😁
