### ISSUE TITLE
Comment highlighting

### ISSUE THREAD

**Issue by inspiredlabs** [fabiospampinato/vscode-highlight#21]
Is there a regex combination to add where any commented code, from any filetype becomes highlighted?

For example, highlight the common syntax: `FIXME`, `TODO` or `@CRITICAL` inside of day-to-day comments inside: `*.SVG`, `*.JS` or `*.Elm`?

Thanks for this – it's great to see markdown everywhere!

**Comment by fabiospampinato** [comment]
Nope, `vscode-highlight` gives you the tool for highlighting via regexes, but it doesn't highlight anything for you by default, how could he know what you want to highlight.

**Comment by fabiospampinato** [comment]
If you read the readme I've already included a quite complicated regex for matching TODO comments, it's basically the one I'm using. If you need to highlight anything else you'll have to write a regex for it, I recommend you to use https://regex101.com when writing regexes.

**Comment by inspiredlabs** [comment]
Suggested snippet from the "Demo" section in the documentation: [https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight#overview](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight#overview), is not clear exactly where to edit. Saving a snippet in `~Library/Application Support/Code/User` returns "Unknown configuration setting" in the console – obviously the, wrong place.

Next try was in the Extensions panel under: `highlight.decorations`, copy/pasting the snippet in "Workspace Settings" returns no errors in the console, nor highlights the code comments as in the Demo. 

`{
	"folders": [
		
		{
			"path": "."
		}
	],
	"settings": {
		
		"highlight.regexes": {
			"(// ?TODO:?)(.*)": [
				{
					"overviewRulerColor": "#ffcc00",
					"backgroundColor": "#ffcc00",
					"color": "#1f1f1f",
					"fontWeight": "bold"
				},
				{
					"backgroundColor": "#d9ad00",
					"color": "#1f1f1f"
				}
			],
			"(// ?FIXME:?)(.*)": [
				{
					"overviewRulerColor": "#ff0000",
					"backgroundColor": "#ff0000",
					"color": "#1f1f1f",
					"fontWeight": "bold"
				},
				{
					"backgroundColor": "#d90000",
					"color": "#1f1f1f"
				}
			],
			"(// )(@\\w+)": [
				{},
				{
					"color": "#4de0ff"
				}
			]
		}
		
	}
}

`

**Comment by fabiospampinato** [comment]
You should the whole readme.

**Comment by fabiospampinato** [comment]
You have to past it in your VSCode settings.

**Comment by inspiredlabs** [comment]
No, that was what was written in the `Readme`.

**Comment by inspiredlabs** [comment]
`{
    "highlight.decorations": { "rangeBehavior": 3 }, // Default decorations from which all others inherit from
    "highlight.regexFlags": "gi", // Default flags used when building the regexes
    "highlight.maxMatches": 250, // Maximum number of matches per regex to decorate
    
    //Object mapping regexes to options or an array of decorations to apply to the capturing groups
    "highlight.regexes": {
      "(// ?TODO:?)(.*)": [
        {
          "overviewRulerColor": "#ffcc00",
          "backgroundColor": "#ffcc00",
          "color": "#1f1f1f",
          "fontWeight": "bold"
        },
        {
          "backgroundColor": "#d9ad00",
          "color": "#1f1f1f"
        }
      ],
      "(// ?FIXME:?)(.*)": [
        {
          "overviewRulerColor": "#ff0000",
          "backgroundColor": "#ff0000",
          "color": "#1f1f1f",
          "fontWeight": "bold"
        },
        {
          "backgroundColor": "#d90000",
          "color": "#1f1f1f"
        }
      ],
      "(// )(@\\w+)": [
        {},
        {
          "color": "#4de0ff"
        }
      ]
    }
}`

**Comment by fabiospampinato** [comment]
Man I'm not sure what you're talking about, this is what my settings look like:

<img width="1440" alt="screen shot 2018-11-09 at 19 45 33" src="https://user-images.githubusercontent.com/1812093/48281823-1d9ec700-e458-11e8-8047-bf18326cc726.png">

**Comment by inspiredlabs** [comment]
Sorry if I've been unclear. Here's two suggestions that might help:
- The `Readme` section titled "[Demo](https://github.com/fabiospampinato/vscode-highlight)" is not obvious because you provide a copy/paste snippet that relies on the section titled "Settings". If this was rolled into one copy/paste snippet it'd work exactly like your screenshot.
- It might make sense just to add the "Demo" snippet into the initial install. This way people could see that it works right away.

**Comment by fabiospampinato** [comment]
Thanks for the suggestions but I think it's ok like this, you can see the demo just by scrolling down, and if you read parts of the readme and expect to know how it all works it's your fault.

**Comment by deadcoder0904** [comment]
Hey, @fabiospampinato I use this extension & love it.

Can you post your config here so I can copy-pasta? I definitely don't want to spend a lot of time customizing it & yours look good as seen [here](https://github.com/fabiospampinato/vscode-highlight/issues/21#issuecomment-437456870) 👌

**Comment by fabiospampinato** [comment]
@deadcoder0904 here you go:

```json
  "highlight.regexFlags": "gi",
  "highlight.regexes": {
    "((?:<!-- *)?(?:#|//|/\\*+|<!--|--|\\* @|{!|{{!--|{{!) *TODO(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": [
      {
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f"
      },
    ],
    "((?:<!-- *)?(?:#|//|/\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:FIXME|FIX|BUG|UGLY|DEBUG|HACK)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": [
      {
        "overviewRulerColor": "#cc0000",
        "backgroundColor": "#cc0000",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#cc0000",
        "color": "#1f1f1f"
      }
    ],
    "((?:<!-- *)?(?:#|//|/\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:REVIEW|OPTIMIZE|TSC)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": [
      {
        "overviewRulerColor": "#00ccff",
        "backgroundColor": "#00ccff",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#00ccff",
        "color": "#1f1f1f"
      }
    ],
    "((?:<!-- *)?(?:#|//|/\\*+|<!--|--|\\* @|{!|{{!--|{{!) *(?:IDEA)(?:\\s*\\([^)]+\\))?:?)((?!\\w)(?: *-->| *\\*/| *!}| *--}}| *}}|(?= *(?:[^:]//|/\\*+|<!--|@|--|{!|{{!--|{{!))|(?: +[^\\n@]*?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)|{!|{{!--|{{!))|(?: +[^@\\n]+)?))": [
      {
        "overviewRulerColor": "#cc00cc",
        "backgroundColor": "#cc00cc",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#cc00cc",
        "color": "#1f1f1f"
      }
    ],
    "((?:<!-- *)?(?:#|//|/\\*+|<!--|--|\\* @) *)(@[^\\s]+)((?: +[^@\n]+?)(?= *(?:[^:]//|/\\*+|<!--|@|--(?!>)))|(?: +[^@\n]+)?)?": [
      {},
      {
        "overviewRulerColor": "#aaaaaa",
        "color": "#aaaaaa",
        "fontWeight": "bold"
      },
      {}
    ]
  },
```

**Comment by fnicastri** [comment]
Hi Fabio,
why not include a standard conf for regex?

**Comment by fabiospampinato** [comment]
@fnicastri because different people might want to use the extension for different things.

**Comment by fnicastri** [comment]
@fabiospampinato you are right.
Can I suggest to highlight this on the readme? (pun not inteded...)

**Comment by fabiospampinato** [comment]
@fnicastri I think it should be clear enough already.
