### ISSUE TITLE
instruction feature request

### ISSUE THREAD

**Issue by noktilux** [fabiospampinato/vscode-highlight#23]
as a new user, i was not easy to figure out where to place the syntax/instructions for this (or any) extension.  it would be very useful to have this in the instructions/readme.

in ubuntu, this is the location of the file to edit:
/home/[user]/.config/Code/User/settings.json

from vs code menu:
preferences->settings->extensions ...

**Comment by fabiospampinato** [comment]
IMHO rather than adding some info about this into every single extension's readme this should be more clearly explained by VSCode itself, unfortunately they switched to a graphical settings editor by default in the last release.
