### ISSUE TITLE
Run on specific file types only

### ISSUE THREAD

**Issue by borup3** [fabiospampinato/vscode-highlight#24]
I like this extension, as it enables me to add custom language highlighting without navigating VS Code's bad architecture of mixed concerns between language support and language/theme coloring.

Can a setting be added to this so it only runs on specific file types? For example, my settings.json is practically unreadable now.

**Comment by fabiospampinato** [comment]
This is already supported, check the `filterLanguageRegex` option.

**Comment by borup3** [comment]
Thanks. This is not a file type but a language extension name. I would prefer to not have to create a language extension to carry around with me just to use this feature. Is a file type possible?

**Comment by fabiospampinato** [comment]
@borup3 I'm not sure I'm understanding correctly what you're saying. You can filter languages via `filterLanguageRegex` and filepaths via `filterFileRegex`. If that's not enough what are you trying to filter out exactly?

**Comment by borup3** [comment]
filterFileRegex sounds like what I'm looking for (run on e.g. "*.ext" files). These options aren't well documented or exposed via settings, so I didn't find them. Thanks, I'll try that one.

**Comment by taodaqiao** [comment]
"highlight.regexes": {
    "(//TODO)(:)": [
      { 
        "regexFlags": "g", 
        "filterLanguageRegex": "MyMam", 
        "filterFileRegex": ".*\\.mam", 
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "textDecoration": ";font-family:arial",
        "color": "red",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#ffcc00",
        "color": "green"
      }
    ]
  }

Is this wrong? It is invalid.

**Comment by fabiospampinato** [comment]
@taodaqiao maybe you have to escape those slashes 🤔 If that doesn't work format it properly and I'll try it myself.

**Comment by taodaqiao** [comment]
"highlight.regexes": {
    "(// ?TODO:?)(.*)": [
      {
        "regexFlags": "g", 
        "filterLanguageRegex": "mam", 
        "filterFileRegex": ".*\\.mam", 
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      }
    ]
}
It is invalid，Can't filter

**Comment by taodaqiao** [comment]
`"highlight.regexes": {
    "(// ?TODO:?)(.*)": [
      {
        "regexFlags": "g", 
        "filterLanguageRegex": "mam", 
        "filterFileRegex": ".*\\.mam", 
        "overviewRulerColor": "#ffcc00",
        "backgroundColor": "#ffcc00",
        "color": "#1f1f1f",
        "fontWeight": "bold"
      },
      {
        "backgroundColor": "#d9ad00",
        "color": "#1f1f1f"
      }
    ]
}` @fabiospampinato
