### ISSUE TITLE
[feature request] Adding a 2px of corner radius should look better

### ISSUE THREAD

**Issue by RayPS** [fabiospampinato/vscode-highlight#28]
```json
{
    "highlight.cornerRadius": true
}
```

**Comment by fabiospampinato** [comment]
We do support all decorations supported by VSC, no need for any extra options.

**Comment by RayPS** [comment]
Sorry, I should read the doc carefully.

**Comment by HassanAzzam** [comment]
@RayPS Did you find a way to do this?

**Comment by fabiospampinato** [comment]
@HassanAzzam Read the readme, and then read this: https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions
