### ISSUE TITLE
Setting the font family

### ISSUE THREAD

**Issue by rolandleth** [fabiospampinato/vscode-highlight#30]
Hey,

Would it be possible to add an option to change the font family? Looked through the source code, but I sadly can't figure it out :(

Thanks!

Edit: After checking https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions it seems there isn't any, right?

**Comment by fabiospampinato** [comment]
In theory that's not possible, but in practice I think you can kind of inject pretty much arbitrary CSS via those decorators, for instance try to set this:

```
"textDecoration": ";font-family:arial"
```

I think if you still use a monospace font perhaps this could be usable 🤔.

**Comment by rolandleth** [comment]
HA! That worked, thank you, Fabio! 👏🏻
