### ISSUE TITLE
How can I highlight word "<?php"

### ISSUE THREAD

**Issue by Byzz91** [fabiospampinato/vscode-highlight#32]
`"(?:<\\?php)"`

"<?php" word could not highlighting word.

how can I highlight word by regex?

thanks.

![image](https://user-images.githubusercontent.com/17328737/58063083-ab9dfc00-7bb7-11e9-8c45-5ca27055b4c1.png)

**Comment by fabiospampinato** [comment]
You need a capturing group, that's not a capturing group.

**Comment by Byzz91** [comment]
@fabiospampinato thanks!! have a nice day :)

**Comment by fabiospampinato** [comment]
No problem, you too :)
