### ISSUE TITLE
Use matching groups in decorators

### ISSUE THREAD

**Issue by SandyGifford** [fabiospampinato/vscode-highlight#33]
I use Highlight to quickly label my files with syntax-free colors when I'm jumping around between lines.  This leaves me with a pretty verbose configuration:

```JSON
"highlight.regexes": {
	"(//FLAG red)": [ { "color": "red" } ],
	"(//FLAG green)": [ { "color": "lime" } ],
	"(//FLAG blue)": [ { "color": "cyan" } ],
	"(//FLAG yellow)": [ { "color": "yellow" } ],
},
```

This works, but is a little limited (I often find myself wanting more than however many colors I've pre-arranged in my config, or wanting to add colors similar to existing ones to do some categorization).

What I'd really love to be able to do is reference matching groups in the decorators:

```JSON
"highlight.regexes": {
	"(?://FLAG) (.+)": [ { "color": "{match:1}" } ],
}
```

**Comment by fabiospampinato** [comment]
This is too specific. Besides you'r using `cyan` for `blue` anyway. I'd say define a bunch of them at once and forget about it.

**Comment by SandyGifford** [comment]
not trying to argue for a re-open (too specific is too specific) but this is just an abridged version of my config - if matching groups were implemented I wouldn't have a problem with typing `//FLAG cyan` if that's the color I wanted.

**Comment by fabiospampinato** [comment]
I see your point, but this is too specific, I can't think of any other practical use case for this, and this is also the first time this feature has been requested.

**Comment by SandyGifford** [comment]
All totally fair points.  Thanks for the great add-in!

**Comment by fabiospampinato** [comment]
Actually I changed my mind on this. I still think this is would be a narrow in scope feature, but all front-end developers deal with colors of one sort of another, and being able to colorize those would be useful. Also I'm currently using another extension for this specific need and it's pretty bad in terms of performance.

I'd be happy to consider a PR that adds support for using matching groups in decorators, basically replacing things like `$0`, `$1` etc. :+1:

**Comment by SandyGifford** [comment]
I'll see if I can get some time!  Thanks for reconsidering!

**Comment by fabiospampinato** [comment]
Implemented, check it out: https://github.com/fabiospampinato/vscode-highlight#colors
