### ISSUE TITLE
Highlight not limited to capture groups

### ISSUE THREAD

**Issue by celynwalters** [fabiospampinato/vscode-highlight#34]
Great extension, thanks!

Having this example in my settings:
```json
"highlight.regexes": {
	"message\\((.*)\\).*": [{
		"backgroundColor": "#859900",
		"overviewRulerColor": "#859900"
	}]
}
```
results in 

![Screenshot from 2019-08-12 13-32-01](https://user-images.githubusercontent.com/3299161/62865175-a8716280-bd05-11e9-9b96-909a53bc1631.png)

where the highlighted section is the length of the bracket contents (updates while typing).

I can achieve what I want using a lookbehind, `"(?<=message\\()(.*)\\).*"` but it's more unwieldy.
I could also use an empty capturing group first, but I then have to undo the global decorations option I have set.

Is this intended behaviour?

**Comment by fabiospampinato** [comment]
Read the readme carefully, that configuration is invalid as far as the extension is concerned.

> Note: All characters of the matched string must be wrapped in a capturing group, and for each capturing group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.
