### ISSUE TITLE
Can't use regex patterns that contain illegal json escape sequences

### ISSUE THREAD

**Issue by TinyAtoms** [fabiospampinato/vscode-highlight#35]
First of all, lovely extension. I discovered this a few days ago, and I'm loving it so far.  Thanks for creating it!

The one problem I'm having is that I basically can't include `\w, \W, \D, \d, \(` in my patterns, because vscode will complain that I have an "Invalid escape character in string.", and then (sometimes) hang till I kill it via task manager.

Have you thought about storing the sequences and their settings in another file that's not settings.json, or perhaps not in a json file?

One one hand, I don't really _need_ it, but I'm sure the extension would be a lot more powerful if we could use these.

I was really hoping I could use 
`(PLAN:?)((.*\s)*END)`.
and such.

**Comment by fabiospampinato** [comment]
You can use basically any string possible, escaping a string don't create forbidden strings or something.

I think you should escape your backslash in this situation, so you should probably use:

```
(PLAN:?)((.*\\s)*END).
```

**Comment by TinyAtoms** [comment]
Oh wow, I wonder why that didn't even enter my head. I feel silly now. 
Well, thanks for the fast response!
