### ISSUE TITLE
cannot change color themes anymore when using the Highlight extension

### ISSUE THREAD

**Issue by hiccup2** [fabiospampinato/vscode-highlight#36]
Hi Fabio,

Thanks for creating the Highlight extension for Visual Studio Code!

I am grateful since it looks like it will make it possible to do exactly what I am aiming for, but I am running into a problem with it.

To try it out first, I found your example demo code for TODO and FIXME by opening the extensions panel, and added that code to the existing code in settings.json
(I added it at the end, right after the existing "workbench.colorTheme": ..."
That worked perfectly.

But as soon as I now want to change a color theme, VSC displays an error popup saying: " Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again."

Only when I remove your code from settings.json I can change themes again.

Am I doing something stupid? (I am not an experienced or talented coder at all, and this json stuff is completely new to me), or is there perhaps some bug regarding this?

cheers! Jist

**Comment by fabiospampinato** [comment]
> " Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again."

I'm not sure what this means, this is a problem with VSCode, not with the extension.

Maybe you have your unsaved settings open while you're trying to change theme?

**Comment by hiccup2** [comment]
Wow you're fast!
No, I saved the settings.json, closed all tabs exept the one I am working on, and restarted VSC.

**Comment by hiccup2** [comment]
Issue closed?

Ok, no problem. I removed your Highlight extension and VS Code is working well again.
Maybe I'll try it again next year to see if the extension is less buggy.

**Comment by fabiospampinato** [comment]
I've closed it because it's not an issue with the extension.

**Comment by serkanyersen** [comment]
I noticed this issue. for me it only happens if you have `?` in your regexp.

`?` inly works if you escape it `\?` and vscode doesn't like escaped question mark. Remove ? and everything works again.
