### ISSUE TITLE
Highlighting stops after 250 matches

### ISSUE THREAD

**Issue by JonathanTroyer** [fabiospampinato/vscode-highlight#37]
![image](https://user-images.githubusercontent.com/15098499/68039506-438d2f00-fc9a-11e9-8a85-61db8306873e.png)

Settings.json
```json
"highlight.regexes": {
    "(<td)": [
        {
            "outline": "1px solid #19c2ff",
        }
    ]
}
```

**Comment by fabiospampinato** [comment]
Set the `highlight.maxMatches` setting accordingly, it's set to 250 by default to avoid crashing the editor with explosive regexes.

**Comment by JonathanTroyer** [comment]
Might wanna put that in the docs.

**Comment by fabiospampinato** [comment]
It's in the docs already.
