### ISSUE TITLE
Regex lookahead

### ISSUE THREAD

**Issue by mbelogubov** [fabiospampinato/vscode-highlight#38]
Hi. I want to highlight double spaces.
My regex here https://regex101.com/r/VwutwN/8 shows expected result:
![image](https://user-images.githubusercontent.com/55445773/70022657-6323ba00-15ae-11ea-8ded-1a3c195fc901.png)

Actual result is VS Code:
![image](https://user-images.githubusercontent.com/55445773/70022531-ea246280-15ad-11ea-959d-b51a8ff98940.png)
My config:
```
{
    "highlight.decorations":
    {
        "rangeBehavior": 3,
        "color": "#ffff00",
    },
    "highlight.regexFlags": "gmi",
    "highlight.maxMatches": 250,
    "highlight.regexes": {
        "(^(?! *\\*| *//)[^\n]*\\S(  +)\\S)": {
            "decorations": [
                {
                    "color": "white",
                },
                {
                    "color": "lime",
                },
                {
                    "color": "blue",
                }
            ],
        },
    }
}

```
Looks like there is an group position offset issue.

**Comment by fabiospampinato** [comment]
> Note: All characters of the matched string must be wrapped in a capturing group, and for each capturing group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.

**Comment by mbelogubov** [comment]
Maybe I do something wrong.
Made simple examples to be more obvious.
![image](https://user-images.githubusercontent.com/55445773/70638968-311bf300-1c53-11ea-8fd0-a3cbcad1867c.png)
![image](https://user-images.githubusercontent.com/55445773/70638929-26615e00-1c53-11ea-806f-626d7561f1f2.png)

**Comment by fabiospampinato** [comment]
Well there's also this tidbit in the readme:

> Note: Nested capturing groups are not supported.

you should rather have something like `"(s)(  )(h)"`

**Comment by mbelogubov** [comment]
Wrapping each part to group helped.
Final regex is

> (^(?! *\\*| *//)[^\n]*\\S)(&nbsp;&nbsp;+)(\\S)

Thanks for help and for this great extension!
