### ISSUE TITLE
Unable to recognize regex that begin with a backslash

### ISSUE THREAD

**Issue by nickolasb** [fabiospampinato/vscode-highlight#39]
While trying to highlight things like "\null" or "\result" I noticed that the extension can't highlight the initial backslash.

A config that I tried was:
```
"(\\exists|\\forall|\\lambda|\\max|\\nothing|\\null|\\old|\\result|\\sum|\\valid)()": [
{
"color": "#3dc0ff"
},
{
}
],
```
But nothing all words worked well. Something weird is happening.

**Comment by fabiospampinato** [comment]
You have to **double** escape things, once for JSON and the other time for the regex, so write `\\\\`.
