### ISSUE TITLE
Leading `^` seems not to take effect

### ISSUE THREAD

**Issue by neilsustc** [fabiospampinato/vscode-highlight#4]
I am trying to use these patterns `^(> )`, `(^> )` to match the Markdown quote block. But none of them takes effect.

**Comment by neilsustc** [comment]
Okay, I know the difference. Your extension execute a match across the whole document. So only <code>\> </code>at the beginning of the document instead of every line will be found.

I changed it to `\\n(> )` then it works as I expected. Thanks

**Comment by fabiospampinato** [comment]
@neilsustc I think you can change this by replacing:

```
 "highlight.regexFlags": "gi"
```

with:

```
 "highlight.regexFlags": "gmi"
```

Maybe I should make those the default flags 🤔

**Comment by fabiospampinato** [comment]
@neilsustc using `((?:\\n|^)> )` instead should make it work for both cases.

**Comment by neilsustc** [comment]
Good tips 😀

**Comment by neilsustc** [comment]
After some trials, I find that adding `m` flag is the best solution.
Using `\\n` with a colored border will result this

![image](https://user-images.githubusercontent.com/7588612/39083427-199815e6-4596-11e8-9b5d-b8faee9ff526.png)

**Comment by fabiospampinato** [comment]
Another way of fixing that would be to wrap `\\n` in a capturing group of its own and supply an empty object as its decorations, basically I think this should work too:

```json
"highlight.regexes": {
  "(\\n|^)(> )": [
    {},
    {
      "backgroundColor": "green",
      "border": "1px solid yellow"
    }
  ]
}
```

**Comment by neilsustc** [comment]
You are right
