### ISSUE TITLE
Standalone settings file

### ISSUE THREAD

**Issue by jadnhm** [fabiospampinato/vscode-highlight#40]
It would be awesome if the `highlight.regexes` could be in a separate file. 

Perhaps the config in settings.json could specify a path that would point to the discrete highlight settings file?

**Comment by fabiospampinato** [comment]
PR welcome for adding support for a `.vscode/highlight.json` too.

**Comment by fabiospampinato** [comment]
Actually this is unnecessary and doesn't really bring much value.
