### ISSUE TITLE
Can it cause performance issues if used too much?

### ISSUE THREAD

**Issue by chavlji** [fabiospampinato/vscode-highlight#41]
I'd like to use this extension to highlight Vue based html properties like `v-model`, `v-if`.
Give special color to `class` and `data-*` attributes, and so on...

Extending html/vue grammer is a bit too much for me and with this extension I can do exactly what I want.

My question is, is this extension meant more for here and there highlighting, and will it cause performance issues if i use it widely? (eg. to highlight 500 matches in a single file)

**Comment by fabiospampinato** [comment]
Try it and see.

I'd say performance is pretty good overall, I haven't personally had any issues with it and I'm running some complicated regexes through it.

The 250 default limit is there to avoid the case where one writes a broken regexes that has a gazillion matches and the thing crashes.
