### ISSUE TITLE
Cannot find the configuration file to configure my own settings

### ISSUE THREAD

**Issue by earik87** [fabiospampinato/vscode-highlight#43]
Thanks for this extension, but I couldn't make it work.

I am looking for the configuration file for the highlight settings. however, I cannot see them. 

Readme.md is not very intuitive. Can you help?

**Comment by fabiospampinato** [comment]
There's no standalone settings file for this extension, you have to put the mentioned settings in VSCode's settings.

**Comment by earik87** [comment]
Thanks! Maybe readme file could be updated with an additional text;

`There is no standalone settings file for this extension. After installing the extension, place the following code into the VSCode Settings to make the extension work. `

**Comment by fabiospampinato** [comment]
I think that is kinda superfluous as most extensions work that way.

**Comment by chavlji** [comment]
I have 300+ rules and it clutters my settings.json :(
