### ISSUE TITLE
Not decorating the last char of a line

### ISSUE THREAD

**Issue by z7z8th** [fabiospampinato/vscode-highlight#46]
This is quite the flexible extension I needed.
Though there's a  little problem with it, sometimes the last char of a line is not decorated, sometimes decorated, sometimes the semi-colon is not decorated correctly.
<img width="482" alt="Screen Shot 2020-03-29 at 10 18 48 AM" src="https://user-images.githubusercontent.com/576241/77838465-e80e9100-71a6-11ea-9823-fcb7a4ed9e6a.png">
<img width="345" alt="Screen Shot 2020-03-29 at 10 18 32 AM" src="https://user-images.githubusercontent.com/576241/77838466-ea70eb00-71a6-11ea-82e2-41e67163d10e.png">

My setting is as follows:
```json
    "highlight.regexFlags": "mgi",
    "highlight.regexes": {
        "(#|-{2,}|/{2,}|/\\*)?(?:\\s*)((?:TODO|FIXME|NOTE|CAUTION|BUG):?|\\[warn\\])(.*)": {
            "decorations": [
                { "color": "white", "backgroundColor": "green" },
                { "color": "white", "backgroundColor": "tomato" },
                { "color": "white", "backgroundColor": "#9A7D0A" }
            ]
        },
        "(\\[error\\].*)": [
            { "color": "lightgray", "backgroundColor": "#F004" }
        ],
        "(\\[(?:crit|alert|emerg)\\].*)": [
            { "color": "white", "backgroundColor": "#F0F" }
        ]
    },
    "highlight.decorations": {
        "rangeBehavior": 1
    }
```

Thank you

**Comment by fabiospampinato** [comment]
Read the readme more carefully:

> All characters of the matched string must be wrapped in a **capturing** group.
