### ISSUE TITLE
Match seems to have an offset

### ISSUE THREAD

**Issue by yar00001** [fabiospampinato/vscode-highlight#47]
Say I have this line I want to match:

`  - [Link](url) {rev}
`

Using this regex (un-escaped)
`(-)[s*]([)(.*)(])((.*))(?=(.)*{rev})
`
With this setting:

```
    "(\\-)[\\s*](\\[)(.*)(\\])(\\(.*\\))(?=(.)*\\{rev\\})" : {
      "filterLanguageRegex": "markdown",
      "regexFlags": "g",
      "decorations": [
        {},
        {},
        {"color": "#719c52"},
        {},
        {}
      ]
    }
```

What I expect to see is only third group to change the color ([regex preview here](https://regex101.com/r/MQwGKL/1)), Although this is what I am seeing (green chars are the matched ones):

![Screen Shot 2020-03-29 at 5 10 52 PM](https://user-images.githubusercontent.com/2102983/77864910-44da6d80-71e0-11ea-87f3-3797ee8282c4.png)

**Comment by fabiospampinato** [comment]
Read the readme: https://github.com/fabiospampinato/vscode-highlight#warnings
