### ISSUE TITLE
Case sensitivity?

### ISSUE THREAD

**Issue by Leedehai** [fabiospampinato/vscode-highlight#5]
It seems the extension is case-insensitive. I wish it is case sensitive.
<img width="295" alt="screen shot 2018-04-27 at 15 41 58" src="https://user-images.githubusercontent.com/18319900/39387977-ac65682a-4a31-11e8-8c08-82dfae92c3dc.png">
<img width="85" alt="screen shot 2018-04-27 at 15 42 10" src="https://user-images.githubusercontent.com/18319900/39387978-ac815e18-4a31-11e8-983e-baf35db64877.png">
<img width="64" alt="screen shot 2018-04-27 at 15 42 16" src="https://user-images.githubusercontent.com/18319900/39387979-ac9695b2-4a31-11e8-9eda-0e7610499392.png">

**Comment by fabiospampinato** [comment]
@Leedehai There's an option for this.

By default the flags used when building the regex are "gi", "i" meaning case-insensitive. If you don't want that you have to put this into your settings:

```json
 "highlight.regexFlags": "g"
```
