### ISSUE TITLE
Support other styles like bold/italic

### ISSUE THREAD

**Issue by mojo2012** [fabiospampinato/vscode-highlight#50]
Hi, thanks for this awesome extension!
To make it even better, it would be nice to have other customization options besides the font color. At least bold/italic should be supported. But maybe also underlining or other text effects.

Keep up the good work.
Cheers
Matti

**Comment by fabiospampinato** [comment]
We can't really add any more decorations than the one vscode itself supports, you can try this trick though: https://github.com/Microsoft/vscode/issues/9078#issuecomment-390512079

**Comment by mojo2012** [comment]
Thanks that's awesome :-)

**Comment by RaulDurand** [comment]
Can underline be added?
