### ISSUE TITLE
Highlighting trailing whitespaces

### ISSUE THREAD

**Issue by MichaelLontke** [fabiospampinato/vscode-highlight#58]
Hi, I am trying to highlight trailing whitespaces with this configuration but unfortunately it won't work:
```
    "highlight.regexes": {
        "([ \t]+$)": [
            { 
                "backgroundColor": "#ffcc0088",
                "color": "white"
            }
        ]
    }
```

**Comment by fabiospampinato** [comment]
You might need to escape that backslash.

**Comment by MichaelLontke** [comment]
I also tried escaping it with `([ \\t]+$)` already.
I played around with it a bit and it looks like it has problems with '$'. trying to escape '$' once or twice also didn't do the trick. If '$' is missing it works fine.

**Comment by MichaelLontke** [comment]
It works now. I was missing the 'm' flag for regex.

BR and have a nice day!

**Comment by fabiospampinato** [comment]
👍
