### ISSUE TITLE
Multiline highlighting

### ISSUE THREAD

**Issue by 6770460** [fabiospampinato/vscode-highlight#59]
Hello! Thank you for great extension!

I faced an issue, trying to highlight the multiline comment block.

Example from Notepad++:
![Снимок экрана 2020-09-27 225036](https://user-images.githubusercontent.com/71987285/94374330-324fdb00-0114-11eb-88b9-3f8207639a14.png)

I try this, but it works only for single-line comment:
![Снимок экрана 2020-09-28 142915](https://user-images.githubusercontent.com/71987285/94426948-0295e700-0197-11eb-9d2e-a3e88cbdc9a5.png)

Is it possible to highlight the multiline blocks in current verison?

**Comment by gnat** [comment]
Was this ever solved? Seems like it never worked.

**Comment by noisnemid** [comment]
wrong key. it should be written like this:

```
 "(/\\*.\\n*\\*/)": {
    ...
}
```
