### ISSUE TITLE
Include/exclude file type per regex

### ISSUE THREAD

**Issue by Geobert** [fabiospampinato/vscode-highlight#6]
Hi,

I was wondering if it is possible to include/exclude file type per regex?

I want some hightlight everywhere, some only on code file, some only on markdown etc…

**Comment by fabiospampinato** [comment]
It's not possible at the moment, but this is a feature I'll implement on the next release (I need to find the time for this though).

**Comment by fabiospampinato** [comment]
Implemented in v1.2.0.

**Comment by Blutti** [comment]
As far as I can tell you currently support 'including' regex rules for certain file types, but not excluding them.
E.g. I would like to highlight all 'tab' characters in pretty much all files (2 spaces FTW). Except that that would result in all Makefiles being highlight like a Christmas tree. -> I would like to disable it only for Makefiles.

Would this be (semi-)easily be possible as well?

**Comment by fabiospampinato** [comment]
@Blutti sure, the trick is using negative look-aheads.

Instead of this: 

```
"filterLanguageRegex": "^makefile"
``` 

you should write this:

```
"filterLanguageRegex": "(?!^makefile)"
```

**Comment by Blutti** [comment]
@fabiospampinato There we go. Regex is so much black magic to me :).
I did need to change your suggestion to `"filterLanguageRegex": "^(?!makefile)"`. 
But it works great now. Thanks :D
