### ISSUE TITLE
Highlight Regex applying decorations to non-captured elements

### ISSUE THREAD

**Issue by trexoftsys** [fabiospampinato/vscode-highlight#60]
Hey there! I've been trying out your extension, which is really cool and easy to use, but I've found a rather nasty bug with the highlighting regex - specifically, if I use the regex "(//TODO):(.*)" with the colon character in neither of the captured groups, the decorations from the capturing group following the colon apply to the colon as well even though the colon should have no decorations since I don't want to capture it, and the group following the colon gets one character less of decorations.

Here's a screenshot showing the problem with the colon being 'eaten' by the decoration, along with the configuration:

![Screenshot-31_10_2020-10 56 54](https://user-images.githubusercontent.com/71434536/97775304-426e3680-1b68-11eb-91f4-bb9cddd367ad.jpg)

In the above example, I don't want the colon to be decorated, which is why I didn't put it in any capturing group, but the decorations get applied to it either way, while leaving the last group partially undecorated :(

**Comment by trexoftsys** [comment]
Also, apparently the only way to go around this bug is by putting the things that I don't want to capture inside a captured group that will have no decorations whatsoever.

**Comment by fabiospampinato** [comment]
Read the readme:

> All characters of the matched string must be wrapped in a capturing group.

> For each capturing group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.

PR welcome to remove this limitation, but it kind of requires shipping a custom regex engine with the extension so...
