### ISSUE TITLE
Using "backgroundColor" removes VSCode's selection highlight and cannot see what I select

### ISSUE THREAD

**Issue by trexoftsys** [fabiospampinato/vscode-highlight#61]
Hey!

Every time I use the "backgroundColor" property, the colored text doesn't show the selection box for what I selected, so I have no idea what I selected :( 

It feels like this property overrides the whole text selection behavior, making selections invisible on the color-highlighted text.

![Screenshot-31_10_2020-18 02 50](https://user-images.githubusercontent.com/71434536/97783901-6864fc80-1ba3-11eb-9649-d19ddc95b45d.gif)

**Comment by fabiospampinato** [comment]
It sounds like you should report this in vscode's repo?

I can't really do anything about that, I can only suggest you to set a more transparent background color, maybe that would help.

**Comment by trexoftsys** [comment]
I've tried using transparent colors, but it doesn't work - it works only when I don't use "backgroundColor".

**Comment by trexoftsys** [comment]
Actually, if I use true transparency via rgba, it seems to show something - thank you for the suggestion! :)
