### ISSUE TITLE
regex start character" ^ " doesn't work, how to write regex that begin with some character

### ISSUE THREAD

**Issue by idealsu** [fabiospampinato/vscode-highlight#63]
HI~

# my purpose
write **^\d.*** to math below line:

1 aaa
2, bbb
3，ccc

# my config section is: 

		"(^\\d.*)": [
			{
				"color": "#ff5424"
			}
		]
# result:
but, nothing matched, what wrong with my config?

**Comment by fabiospampinato** [comment]
the regex is wrong, it should be something like `(^.*\\d.*)`, and you have to make sure that the "m" flag is set.
