### ISSUE TITLE
Ability to change opacity of current text color

### ISSUE THREAD

**Issue by alex-che** [fabiospampinato/vscode-highlight#65]
I use your extension to dim logging statements in my source code (i.e., for kinda purpose which is an opposite to the extension name). Currently I set the `color` property to be close to current theme background color. It has some cons:
1. Works only for some themes.
2.  Breaks current language syntax highlighting.

It would be perfect to be able to add some `opacity` property to allow changing current text opacity without overriding its color. 
Not sure if vscode API allows it though.

**Comment by fabiospampinato** [comment]
I can't add any more decoration properties than the one already available, this is something you should ask to the vscode folks.

**Comment by alex-che** [comment]
@fabiospampinato I'm sorry, I'm an idiot. The VS Code API has exactly this decoration property with the exactly this name: `opacity`.

So, this configuration does exactly what I want:

```
   "highlight.regexes": {
      "(APP_LOG_DEBUG\\(\\) <<[^;]+;)": {
         "regexFlags": "mg",
         "filterLanguageRegex": "cpp",
         "decorations": [
         { "opacity": "0.5" }
         ]
      }
   }
```

![image](https://user-images.githubusercontent.com/4246686/103134409-17b0e200-46c2-11eb-92ee-4f050be964a4.png)


P.S.: Thanks for your fabulous extension, Fabio!
