### ISSUE TITLE
Don't change whitespaces color

### ISSUE THREAD

**Issue by alex-che** [fabiospampinato/vscode-highlight#66]
I have the `View -> Render Whitespace` vscode option turned on. So, all the vscode whitespace marks within my highlight regex capture change their color. It would be nicer to have an option to skip coloring whitespaces within a capture.

![image](https://user-images.githubusercontent.com/4246686/103042506-e681c600-458a-11eb-8b0a-1ba8a2f3b70f.png)

**Comment by fabiospampinato** [comment]
Change your regexes in order to provide different decorations for whitespace.

If you are asking for some special decoration properties you should ask this to the vscode folks, I can't really implement that at the extension level.

**Comment by theonenotzero** [comment]
This issue should be reopened. I am trying to highlight everything between a start and end delimiter and currently it also colours the whitespace. It is not possible to change my regex to skip whitespace because of the nature of the rule.

**Comment by kymikoloco** [comment]
This seems really odd to me that it's coloring the whitespace too.

But here's how I kind of solved it for the default dark (Dark+) theme. Just put the whitespace rule at the top of your regexes with the same color as the existing whitespace.
```

    "highlight.regexes": {
        "(\\s)": [
            {"color": "#404040"}
        ],

**Comment by fabiospampinato** [comment]
> This issue should be reopened. I am trying to highlight everything between a start and end delimiter and currently it also colours the whitespace. It is not possible to change my regex to skip whitespace because of the nature of the rule.

You don't have to skip it, you can match it and provide an empty decoration object for it.
