### ISSUE TITLE
span full width

### ISSUE THREAD

**Issue by kimaldis** [fabiospampinato/vscode-highlight#67]
Is there a way to make the background colour of a highlighted item span the window's full width?

**Comment by fabiospampinato** [comment]
Does the matched item span the entire line?

**Comment by kimaldis** [comment]
As in the style parameter 'iswholeLine' in the todohighlight extension for VSC. the matched item, in that case, doesn't have to fill the whole line:

<img width="744" alt="Screenshot 2021-02-10 at 20 14 06" src="https://user-images.githubusercontent.com/4265299/107566414-c78fcf80-6bdc-11eb-8e4f-86365d70c518.png">

**Comment by fabiospampinato** [comment]
Oh yeah there's a "isWholeLine" property that you could set as a decoration https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions
