### ISSUE TITLE
Provide some default decorations

### ISSUE THREAD

**Issue by vhesener** [fabiospampinato/vscode-highlight#69]
This is an extra credit suggestion for a great extension. Nothing critical nor necessary.

Maybe you don't want to be too opinionated on the styles people use, but I think a majority want what they see in your screenshots, at least by default. I think the regex that you put so much work into is great and the colors for TODO and FIXME seem reasonable. 

If anything, maybe have some of the options take union types of predetermined regex expressions (e.g. `'highlightTodo' | 'highlightTodoAndBody' | 'boxTodo' ...`) and run a switch statement on them in the implementation?

**Comment by fabiospampinato** [comment]
Maybe it could make sense, although this extension is agnostic about what should be highlighted.

**Comment by vhesener** [comment]
Agree, and never compromise on that principle. You can still maintain agnosticism while providing convenience via sensible defaults. I like the defaults you chose and I believe others do too. Option defaults are perfect for being both prescriptive and agnostic at the same time.

**Comment by fabiospampinato** [comment]
Implemented in 1.5.0.

**Comment by jd-0001** [comment]
@fabiospampinato How to disable default decorations, I am already using another highlighter for todos and I want to use this extension to highlight specific words
