### ISSUE TITLE
color modification decoration

### ISSUE THREAD

**Issue by basaran** [fabiospampinato/vscode-highlight#71]
Hello, not sure if this is possible but please allow me to explain my use case. I was trying to improve quality of code documentation with my js files. So, I decided to replace most of my comments with debugs. But they were too shiny, luckily that led me to your extension which helped a great deal. Later in the story, I tried to make things a little fancier by taking advantage of the additional decorators.

```
        "(debug\\(.*)": [
            { "color": "#5e5e5e", "letterSpacing" : "-1px", "before" : {"contentText" : "☀ "}},
        ],
```

![image](https://user-images.githubusercontent.com/30809170/111866282-b86e1100-8942-11eb-94b1-0d725f528923.png)

Would it be possible to color that unicode character?

**Comment by magiruuvelvet** [comment]
According to the documentation which is linked in the README btw. https://code.visualstudio.com/api/references/vscode-api#ThemableDecorationAttachmentRenderOptions

This works:
`"decorations": [ { "color": "green", "before" : {"contentText" : "⚙ ", "color": "gray"} } ]`

Inside the `"before"` object just a a color or any other decoration option.

This is the result:

![スクリーンショット_20210326_102646](https://user-images.githubusercontent.com/13280758/112611173-c8dc2b00-8e1d-11eb-800c-1a04cc84f16e.png)

**Comment by basaran** [comment]
thank you very much
