### ISSUE TITLE
[#Request] Fast Enable/Disable tag

### ISSUE THREAD

**Issue by willygroup** [fabiospampinato/vscode-highlight#72]
Hi, 
thanks for your work!

It would be great if we could enable/disable the highlight in the current file with a click in a toolbar containing all the tag (with the relative color).
 - [ ] Done
 - [X] ToDo
 - [X] FixMe
 - [ ] ...
 - [ ] ALL

I've seen that there is already a similar issue: #70 

-- 
Willy

**Comment by fabiospampinato** [comment]
Closing in favor of https://github.com/fabiospampinato/vscode-highlight/issues/70
