### ISSUE TITLE
Advanced TODOs: --debug is flagged as a DEBUG

### ISSUE THREAD

**Issue by rioj7** [fabiospampinato/vscode-highlight#75]
The advanced TODOs have all the text in capitals: TODO, DEBUG,....

But the regex flags used are the `highlight.regexFlags` that default to `"gi"`.

Result: If you have `--debug` in your text it is flagged as a DEBUG Todo.

Remove the `i` from the default regexFlags or add a `"regexFlags": "g"` to the Advanced TODOs in the Readme and config defaults

**Comment by fabiospampinato** [comment]
We want things like `//todo` though. At the end of the day that's ambiguous, if you hit that issue often enough you should use a different regex on your end.
