### ISSUE TITLE
Is filterFileRegex broken?

### ISSUE THREAD

**Issue by gsilvers** [fabiospampinato/vscode-highlight#78]
```JSON
"(TODO:x)(.*)": [
            {
              "overviewRulerColor": "#ffcc00",
              "backgroundColor": "#137A63",
              "color": "#1f1f1f",
              "fontWeight": "bold",
              "filterFileRegex": ".*\\.py"
            },
            {
              "backgroundColor": "#81B69D",
              "color": "#1f1f1f"
            }
          ],
```

Should only apply to .py files correct? Am I using this wrong or is the feature broken?

**Comment by GlebMorgan** [comment]
You're using `filterFileRegex` option in wrong place. You should use it outside `decorations` list. Refer to "Settings" section of extension settings page or just click [here](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight#:~:text=Requires%20double%20escaping%0A%20%20%20%20%22-,filterFileRegex,-%22%3A%20%22.*%5C%5C.ext%22%2C%20//%20Apply%20only).

**Comment by gsilvers** [comment]
Sheeeeeettt I am a dummy
