### ISSUE TITLE
Overrides selection of text?

### ISSUE THREAD

**Issue by dgkimpton** [fabiospampinato/vscode-highlight#79]
As far as I can tell using this extension overrides the selectionBackground colour so that it is impossible to see which text is currently selected within a TODO (or other highlighted block). 

Would it be possible to make this highlighting have lower precedence than selected text?

**Comment by noisnemid** [comment]
Reference merely.

I am not the developer of this extension but I think it'll be a little complicated and there could be an alternative thing which you need some tests.

VSCode itself in fact has some settings items to control the selection background color, but they are not listed in API docs.

as the example shows, you could find some information here https://github.com/Microsoft/vscode/issues/34105

```
"workbench.colorCustomizations": {
        //     "ref": "https://github.com/Microsoft/vscode/issues/34105",
        "editor.background": "#000000",
        // "editor.foreground": "#FFFFFF",
        //     "editor.lineHighlightBackground": "#000000",
        //     "editor.selectionHighlightBackground": "#FF000088",
        "editor.findMatchBackground": "#FF000088",
        "editor.findMatchHighlightBackground": "#e0a607",
        //     "editor.findRangeHighlightBackground": "#00000088",
        //     "editor.selectionBackground": "#30303088",
        //     "editor.inactiveSelectionBackground": "#30303088",
        "editorGutter.background": "#0845c91a"
    },
```
uncomment some lines to see the real effects, and maybe you can find what you are expecting.

**Comment by dgkimpton** [comment]
Sadly I'm already aware of them, but they didn't help. However, I did find a workaround which is to change the Highlight colours (e.g. for TODO) to have an alpha component of about 50%. In this way, I can still see the selection showing through. It's not absolutely ideal but it is workable... which is by far the main thing :)

**Comment by qodo-io** [comment]
To necrobump this: IMHO it is always a good idea to work with extremely low alpha values for backgrounds, as they will blend in better with youtr selected color theme. You can still color the `# TODO` via with first decoration in an more extreme fashion (also: the `overViewRulerColor` might help). But ultimately it's a matter of taste of course

![2021-11-24_11-34-17_@443,87+435x842](https://user-images.githubusercontent.com/38908545/143222435-48d0ee68-4da6-4409-b442-66cefc12a377.png)
![2021-11-24_11-34-50_@447,599+426x335](https://user-images.githubusercontent.com/38908545/143222446-9f5c8b0a-2fbc-4452-8c4a-d475fd65f0b9.png)

**Comment by fabiospampinato** [comment]
Nice suggestions. 

@qodo-io I like your setup!

**Comment by mrtgenet** [comment]
> Sadly I'm already aware of them, but they didn't help. However, I did find a workaround which is to change the Highlight colours (e.g. for TODO) to have an alpha component of about 50%. In this way, I can still see the selection showing through. It's not absolutely ideal but it is workable... which is by far the main thing :)

Hello, how did you proceed ? I tried changing `"backgroundColor": "ffcc00"` to `"backgroundColor": "ffcc0088"` but it does not seem to have any impact
