### ISSUE TITLE
Highlighting within double quotes

### ISSUE THREAD

**Issue by aboey** [fabiospampinato/vscode-highlight#8]
Hi there, I'm trying to change the color of double quoted text in .rmd files. The regex below works, except that the final double quotation mark and the character that precedes it are not highlighted. Is this due to a bad regex?
   
```
"\"([^\"]*?[^\"]*?)\"": {
    "filterFileRegex": ".*\\.rmd",
    "decorations": [
      {
        "color": "#37bf3b"
      }
    ]
  }
```

**Comment by fabiospampinato** [comment]
In the readme it says:

> Note: All characters of the matched string must be wrapped in a matching group, and for each matching group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.

That's not something you're doing.

You might want to replace your configuration with something like this (I haven't tested it), assuming you don't want the quotation marks decorated as well:

```
"(\"\")([^\"]*)(\"\")": {
    "filterFileRegex": ".*\\.rmd",
    "decorations": [
      {},
      {
        "color": "#37bf3b"
      },
      {}
    ]
}
```

Your original regex looks weird to me, I recommend for you to check out https://regex101.com, it's an awesome tool to have around when working with regexes.

**Comment by aboey** [comment]
>In the readme it says:
>
>Note: All characters of the matched string must be wrapped in a matching group, and for each matching group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.
>
>That's not something you're doing.

Thanks for pointing this out; I added the necessary parentheses and it worked 👍
