### ISSUE TITLE
Configure to only highlight certain word from given database?

### ISSUE THREAD

**Issue by Nachtschrecken** [fabiospampinato/vscode-highlight#82]
Hi,
we want to use this extension to just highlight certain methods in different colors depending on their redunancy/energy impact

e.g. in Java a method like System.out.println("hello world") where the println or the whole call should be marked green.

Is there a way to implement this extension that way, to not only highlight todos but configure to also highlight known "words" from a database in a specific color?

Thank you!

**Comment by fabiospampinato** [comment]
Yes, you need to make regexes out of that database to then use in the extension.
