### ISSUE TITLE
Disable donation message

### ISSUE THREAD

**Issue by thomasaarholt** [fabiospampinato/vscode-highlight#85]
Hi! I donated this morning. Is there a way to turn off the donation message (which happens every time I open vscode)? :)

**Comment by thomasaarholt** [comment]
Ah, this might be it. I'm running it in a docker image. My vscode settings (from ~/.vscode) are copied over, however. Where is the fact that the button has been clicked registered/stored?

**Comment by fabiospampinato** [comment]
@thomasaarholt there should be a file specific for the extension either at `~/.local/share/vscode-highlight` or `~/.config/vscode-highlight`. I should add a setting for disabling this though.

**Comment by fabiospampinato** [comment]
I just pushed a release where you can disable the prompt explicitly by setting `donations.disablePrompt` to `true`.

**Comment by thomasaarholt** [comment]
Thanks! I didn't want to complain further, but this has been bugging me :p

**Comment by fabiospampinato** [comment]
It's ok to complain if you have reasons to, especially if you paid for something. Thanks for bringing this to my attention.
