### ISSUE TITLE
feature request: setting for regex to not work inside comments

### ISSUE THREAD

**Issue by TamirCode** [fabiospampinato/vscode-highlight#86]
Since vscode has textmate scope to determine whether anything is a comment or not in any language, I think you should add a setting for a regex to not activate inside comments, would be very useful.

When I say setting I mean exactly like the `"filterLanguageRegex":` setting, which is local to regex and not a general setting

**Comment by fabiospampinato** [comment]
I don't think one can retrieve ranges of textmate scopes programmatically.

Happy to reopen if pointed at the APi that can do that.
