### ISSUE TITLE
FEATURE REQUEST: Add configuration to disable continuous highlighting after typing a matching REGEX

### ISSUE THREAD

**Issue by leandrosiow** [fabiospampinato/vscode-highlight#87]
Example:
Regex to highlight "//TODO"

// TODO
// TODO: asdfasdfasd
             ^ stop highlighting here and not continue after the word TODO
             

Add a configuration such as this to enable/disable the highlighting?

highlight.afterRegex: false | true 

or 

"isWholeLine": false

Thanks.

**Comment by fabiospampinato** [comment]
This is already supported, one of the decorations that you can provide controls what happens when you type at the edge of a decoration. Look again at vscode's docs.
