### ISSUE TITLE
Dollar sign in regex

### ISSUE THREAD

**Issue by janiosarmento** [fabiospampinato/vscode-highlight#88]
I want a regex to highlight variables embedded in strings in Bash. Something like:

`echo "Result: ${result}"`

I need something like:

`(.?\${.*})`

However, I can't escape the `$` sign because VSCode complains of Invalid escape character in string.

How can I achieve my goal, please?

**Comment by janiosarmento** [comment]
The rubber duck never fails!

After asking for help I realized what I needed:

``` 
"(\\${)(.*)(})": {
    "decorations": [
        {

            "fontWeight": "bold"
        },
        {
            "color": "#0496ff"
        },
        {
            "fontWeight": "bold"
        },
    ],
    "filterFileRegex": ".(.*)?sh$"
}
```

Thanks for the very useful extension!

**Comment by janiosarmento** [comment]
Actually, it worked more and less...

A line like:

`echo "${var1}|{$var2}" >> "${logFile}"`

matches the first  `${` and the last `}`, highlighting the entire line, not the tokens as I'd like...

**Comment by fabiospampinato** [comment]
I think you should use `.*?` instead of `.*`
