### ISSUE TITLE
Wrong coloring

### ISSUE THREAD

**Issue by pankleks** [fabiospampinato/vscode-highlight#9]
Following regex:
https://regex101.com/r/QQjP7h/1

works well in regex101

but coloring by extension seems off:
![image](https://user-images.githubusercontent.com/14176066/41485110-7c0873c8-70df-11e8-8679-d848afda2d30.png)

config:
```json
        "\\${([^}]+)}(:[a-z-]+)?": {
            "filterFileRegex": ".*\\.html",
            "decorations": [
                {
                    "color": "lightgreen"
                },
                {
                    "color": "pink"
                }
            ]
        }
```

ext. version: 1.2.0

Thanks for help.

**Comment by fabiospampinato** [comment]
The coloring seems right, your configuration is wrong. In the readme it says:

> Note: All characters of the matched string must be wrapped in a matching group, and for each matching group a decorations options object must be provided (empty decorations are allowed: {}), otherwise the actual decorations will be misaligned.

So your configuration should be (I haven't tested it):

```
        "(\\${)([^}]+)(})(:[a-z-]+)?": {
            "filterFileRegex": ".*\\.html",
            "decorations": [
                {},
                {
                    "color": "lightgreen"
                },
                {},
                {
                    "color": "pink"
                }
            ]
          }
```

**Comment by pankleks** [comment]
Not sure if description is clear.

Anyway thanks - works well. Great extension.

**Comment by fabiospampinato** [comment]
I'm not sure how the wording could be improved, maybe I should add an actual example of what the problem is and how to solve it.

**Comment by pankleks** [comment]
yes - I think it would be better - just keep it simple:)

Thanks again!
