### ISSUE TITLE
Highlight extension supports more than 260 highlight lines?

### ISSUE THREAD

**Issue by althaser** [fabiospampinato/vscode-highlight#90]
Hi,

The extension is working properly with most of files but not working properly with a specific file. This file contains more than 3500 lines and is using like 260 highlight words.

Is there any known limitation regarding the number of words ?

I know this is a bit vague and without debug log but before going in further details I would like to know if this is a limitation.

thanks

**Comment by fabiospampinato** [comment]
There's a configurable limit, which exists not to make the editor crash on bad regexes:

```
  "highlight.maxMatches": 250 // Maximum number of matches to decorate per regex, in order not to crash the app with accidental cathastropic regexes
```
