### ISSUE TITLE
Add rule to highlight digits in text

### ISSUE THREAD

**Issue by GitUser200607** [fabiospampinato/vscode-highlight#91]
When working with complex code from other sources, there could be mistakes with digits in the text like:
`firewall_enable`
and
`firewal1_enable`
Sometimes its hard to notice the error. Is there a quick filter/option to highlight digits in the text with other color?

**Comment by fabiospampinato** [comment]
No actual regex is provided really, you'd have to code whatever you need yourself. 

Maybe you can use something like this:

```
"([a-z_-][0-9][a-z_-])"
```

But I feel like that would also cause a lot of false positives.
