### ISSUE TITLE
space before the capturing group

### ISSUE THREAD

**Issue by jabbalaci** [fabiospampinato/vscode-highlight#96]
I would like to highlight the character `!` (logical not) in some cases:

```
if !v { ... }    // highlight

if a != b    // don't highlight

println!("hello")    // don't highlight
```

That is: if there is a space before the `!` and the character after the `!` is not the equal sign, then highlight the `!`.

This is the version that works for now:

```
"highlight.regexes": {
    "( !)[^=]": [
      { "color": "black", "backgroundColor": "#ffe300", "fontWeight": "bold" }
    ]
  },
```

If I try `" (!)[^=]": ...`, then the space is highlighted and the `!` is not highlighted.

**Comment by fabiospampinato** [comment]
Every single character matched must be part of a capturing group, that's mentioned in the readme.

**Comment by jabbalaci** [comment]
Thank you for the quick reply.

**Comment by fabiospampinato** [comment]
🤣 sorry about that, I'm overwhelmed with stuff to do.
