### ISSUE TITLE
Regexes can't match the start of the line

### ISSUE THREAD

**Issue by Timmmm** [fabiospampinato/vscode-highlight#99]
Presumably the settings in [this comment](https://github.com/mechatroner/vscode_rainbow_csv/issues/14#issuecomment-460996915) worked once, but they no longer do. I tried both `(^#.*)` and `^(#.*)` and neither ever match. `(#.*)` works (but obviously doesn't behave like I want.

**Comment by fabiospampinato** [comment]
I don't think that regex was designed to match the start of a line.

You need to set the "multiline" flag explicitly for "^" to match the start of a line and not the start of a file.

```
  "highlight.regexFlags": "gmi"
```

**Comment by ndjhartman** [comment]
Just some feedback perhaps this should be added to the warnings section on the mainpage, spent some time trying to get my match to work thinking it was an issue with the escaping. Thanks for the extension, very useful!

**Comment by fabiospampinato** [comment]
Good idea, just added 👍
